name: Erin Werner
title: Erin Werner
description: Software Engineer & Data Science Graduate Student

plugins:
- jekyll-remote-theme

remote_theme: benbalter/retlab

lang: en-US

# Pages to include in header navigation
nav_pages:
  - resume.md
  - contact.md
